[2023-12-02 12:43:07 +0200] [5342] [INFO] Starting gunicorn 21.2.0
[2023-12-02 12:43:07 +0200] [5342] [INFO] Listening at: http://127.0.0.1:8000 (5342)
[2023-12-02 12:43:07 +0200] [5342] [INFO] Using worker: sync
[2023-12-02 12:43:07 +0200] [5347] [INFO] Booting worker with pid: 5347
[2023-12-02 12:43:07 +0200] [5347] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'your_project'
[2023-12-02 12:43:07 +0200] [5347] [INFO] Worker exiting (pid: 5347)
[2023-12-02 12:43:07 +0200] [5342] [ERROR] Worker (pid:5347) exited with code 3
[2023-12-02 12:43:07 +0200] [5342] [ERROR] Shutting down: Master
[2023-12-02 12:43:07 +0200] [5342] [ERROR] Reason: Worker failed to boot.
[2023-12-02 12:43:13 +0200] [5368] [INFO] Starting gunicorn 21.2.0
[2023-12-02 12:43:13 +0200] [5368] [INFO] Listening at: http://127.0.0.1:8000 (5368)
[2023-12-02 12:43:13 +0200] [5368] [INFO] Using worker: sync
[2023-12-02 12:43:14 +0200] [5373] [INFO] Booting worker with pid: 5373
[2023-12-02 12:43:14 +0200] [5373] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mhatem/Documents/dashboard-project/backend/dashboardAPI/.venv/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'your_project'
[2023-12-02 12:43:14 +0200] [5373] [INFO] Worker exiting (pid: 5373)
[2023-12-02 12:43:14 +0200] [5368] [ERROR] Worker (pid:5373) exited with code 3
[2023-12-02 12:43:14 +0200] [5368] [ERROR] Shutting down: Master
[2023-12-02 12:43:14 +0200] [5368] [ERROR] Reason: Worker failed to boot.
